# Generated by Django 5.2.5 on 2025-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managementNumber', models.CharField(max_length=50, null=True, unique=True)),
                ('latCrdn', models.CharField(max_length=50, null=True)),
                ('lonCrdn', models.CharField(max_length=50, null=True)),
                ('roadNmAddr', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('baseDate', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
