# Generated by Django 5.2.5 on 2025-08-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laeNm', models.CharField(max_length=100)),
                ('pkplcId', models.CharField(max_length=50, unique=True)),
                ('pkplcNm', models.CharField(max_length=200)),
                ('pklotCnt', models.CharField(max_length=20)),
                ('avblPklotCnt', models.CharField(max_length=20)),
                ('ocrnDt', models.CharField(max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latCrdn', models.CharField(max_length=50, null=True)),
                ('lonCrdn', models.CharField(max_length=50, null=True)),
                ('pkplcNm', models.CharField(max_length=200, null=True)),
                ('pkplcId', models.CharField(max_length=50, null=True, unique=True)),
                ('roadNmAddr', models.CharField(max_length=300, null=True)),
                ('pklotCnt', models.CharField(max_length=20, null=True)),
                ('wkdayOprtStartTime', models.CharField(max_length=20, null=True)),
                ('wkdayOprtEndTime', models.CharField(max_length=20, null=True)),
                ('satOprtStartTime', models.CharField(max_length=20, null=True)),
                ('satOprtEndTime', models.CharField(max_length=20, null=True)),
                ('hldyOprtStartTime', models.CharField(max_length=20, null=True)),
                ('hldyOprtEndTime', models.CharField(max_length=20, null=True)),
                ('parkingBscTime', models.CharField(max_length=20, null=True)),
                ('parkingBscFare', models.CharField(max_length=20, null=True)),
                ('addUnitTime', models.CharField(max_length=20, null=True)),
                ('addUnitFare', models.CharField(max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
